### ISSUE TITLE
重启 management node时，heartbeat把自己从hash ring删掉了，还报错ConcurrentModificationException，但是数据库存在，而且是RUNNING。

### ISSUE THREAD

**Issue by wj5633** [zstackio/zstack#1237]
2018-03-30 09:22:09,187 DEBUG [SimpleFlowChain] {} [FlowChain(FCID_0ee996c2): management-node-bootstrap] successfully executed flow[ManagementNodeManagerImpl.java:node-is-ready]
2018-03-30 09:22:09,198 DEBUG [SimpleFlowChain] {} [FlowChain(FCID_0ee996c2): management-node-bootstrap] start executing flow[ManagementNodeManagerImpl.java:say-I-join]
2018-03-30 09:22:09,206 DEBUG [ConsistentHash] {} the consistent hash ring currently has nodes[2bbb5eb375be472eb4ba07747d264b0a]
2018-03-30 09:22:09,187 DEBUG [SimpleFlowChain] {} [FlowChain(FCID_0ee996c2): management-node-bootstrap] successfully executed flow[ManagementNodeManagerImpl.java:node-is-ready]
2018-03-30 09:22:09,188 DEBUG [SimpleFlowChain] {} [FlowChain(FCID_0ee996c2): management-node-bootstrap] start executing flow[ManagementNodeManagerImpl.java:listen-node-life-cycle-events]
2018-03-30 09:22:09,197 DEBUG [SimpleFlowChain] {} [FlowChain(FCID_0ee996c2): management-node-bootstrap] successfully executed flow[ManagementNodeManagerImpl.java:listen-node-life-cycle-events]
2018-03-30 09:22:09,198 DEBUG [SimpleFlowChain] {} [FlowChain(FCID_0ee996c2): management-node-bootstrap] start executing flow[ManagementNodeManagerImpl.java:say-I-join]
2018-03-30 09:22:09,206 WARN  [ManagementNodeManager] {} management node[uuid:2bbb5eb375be472eb4ba07747d264b0a, hostname: null]'s heart beat has stopped for 3307 secs, add it in suspicious list
2018-03-30 09:22:09,206 WARN  [ManagementNodeManager] {} found that a management node[uuid:5d38fcf801e048abb21f6cb6e4d06d05] had no heartbeat in database but still in our hash ring,notify that it's dead
2018-03-30 09:22:09,206 DEBUG [ConsistentHash] {} the consistent hash ring currently has nodes[2bbb5eb375be472eb4ba07747d264b0a]
2018-03-30 09:22:09,211 DEBUG [ConsistentHash] {} after removing, consistent hash circle has management nodes[2bbb5eb375be472eb4ba07747d264b0a], 500 virtual nodes now
2018-03-30 09:22:09,219 DEBUG [ManagementNodeManager] {} management node is still initializing ...
2018-03-30 09:22:09,227 TRACE [GLock] {} [GLock]: thread[zs-thread-4] is acquiring lock[JobQueueFacade.orphanJobLock]
2018-03-30 09:22:09,231 TRACE [GLock] {} [GLock DB Lock]: thread: zs-thread-4 got DB lock[JobQueueFacade.orphanJobLock], during timeout[60 secs]
2018-03-30 09:22:09,231 DEBUG [JobQueueFacadeImpl2] {} management node[id:5d38fcf801e048abb21f6cb6e4d06d05] starts taking over jobs of left management node[5d38fcf801e048abb21f6cb6e4d06d05]
2018-03-30 09:22:09,328 TRACE [CloudBusImpl2] {} [event publish]: {"org.zstack.core.cloudbus.CanonicalEvent":{"path":"/managementnode/lifecycle","content":{"nodeUuid":"5d38fcf801e048abb21f6cb6e4d06d05","lifeCycle":"NodeJoin","inventory":{"uuid":"5d38fcf801e048abb21f6cb6e4d06d05","joinDate":"Mar 30, 2018 9:22:08 AM","heartBeat":"Mar 30, 2018 9:22:08 AM"}},"managementNodeId":"5d38fcf801e048abb21f6cb6e4d06d05","headers":{"schema":{"content":"org.zstack.header.managementnode.ManagementNodeCanonicalEvent$ManagementNodeLifeCycleData","content.inventory":"org.zstack.header.managementnode.ManagementNodeInventory"},"task-context":{}},"id":"45cf106121ab43408babdb01bde5b7f2","noError":false,"createdTime":1522372929201}}
2018-03-30 09:22:09,329 DEBUG [JobQueueFacadeImpl2] {} [Orphan Queue found]: management node is going to take over 0 orphan queues
2018-03-30 09:22:09,329 TRACE [GLock] {} [GLock]: thread[zs-thread-4] is releasing lock[JobQueueFacade.orphanJobLock]
2018-03-30 09:22:09,331 TRACE [GLock] {} [GLock Release DB Lock] thread[zs-thread-4] released DB lock[JobQueueFacade.orphanJobLock]
2018-03-30 09:22:09,331 TRACE [GLock] {} [GLock Release Memory Lock]: thread[zs-thread-4] released memory lock[JobQueueFacade.orphanJobLock]
2018-03-30 09:22:09,331 WARN  [ManagementNodeManager] {} an error happened when doing heartbeat, null, it's going to recover
2018-03-30 09:22:09,343 DEBUG [SimpleFlowChain] {} [FlowChain(FCID_0ee996c2): management-node-bootstrap] successfully executed flow[ManagementNodeManagerImpl.java:say-I-join]
2018-03-30 09:22:09,344 DEBUG [SimpleFlowChain] {} [FlowChain(FCID_0ee996c2): management-node-bootstrap] successfully completed
2018-03-30 09:22:09,344 TRACE [GLock] {} [GLock]: thread[zs-thread-0] is releasing lock[ManagementNodeManager.inventory_lock]
2018-03-30 09:22:09,334 WARN  [ManagementNodeManager] {} unhandled exception happened
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_144]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1461) ~[?:1.8.0_144]
        at org.zstack.portal.managementnode.ManagementNodeManagerImpl$21.checkAllNodesHealth(ManagementNodeManagerImpl.java:688) ~[portal-2.0.0.jar:?]
        at org.zstack.portal.managementnode.ManagementNodeManagerImpl$21.call(ManagementNodeManagerImpl.java:709) [portal-2.0.0.jar:?]
        at org.zstack.portal.managementnode.ManagementNodeManagerImpl$21.call(ManagementNodeManagerImpl.java:1) [portal-2.0.0.jar:?]
        at org.zstack.core.thread.ThreadFacadeImpl$Worker.call(ThreadFacadeImpl.java:113) [core-2.0.0.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]

**Comment by wj5633** [comment]
2018-03-30 09:22:09,206 WARN  [ManagementNodeManager] {} management node[uuid:2bbb5eb375be472eb4ba07747d264b0a, hostname: null]'s heart beat has stopped for 3307 secs, add it in suspicious list
2018-03-30 09:22:09,206 WARN  [ManagementNodeManager] {} found that a management node[uuid:5d38fcf801e048abb21f6cb6e4d06d05] had no heartbeat in database but still in our hash ring,notify that it's dead

2bbb5eb375be472eb4ba07747d264b0a 是老的UUID
5d38fcf801e048abb21f6cb6e4d06d05  是新的UUID

**Comment by live4thee** [comment]
@wj5633 你是HA环境同时启动多个管理节点？什么版本？最好描述一下环境。

**Comment by wj5633** [comment]
单节点，1.7   场景是management 意外挂掉了，数据库还在，重启management。
我还和master对比了一下ManagementNodeManagerImpl.java文件

**Comment by live4thee** [comment]
@wj5633 本次发布来不及处理，我们下个版本修复。不过 1.7 也太老了。
