### ISSUE TITLE
无法在新加入集群的物理机上创建虚拟机

### ISSUE THREAD

**Issue by xinghui-hou** [zstackio/zstack#1246]
麻烦谁有空能帮忙解答下. 

一台物理机加入集群，只要创建的VM 调度到这台物理机均创建失败 ,创建在别的物理机上正常
创建失败日志如图：
```
{
    "error": {
        "cause": {
            "causes": [],
            "code": "SYS.1006",
            "description": "An operation failed",
            "details": "cannot find the ID for the namespace[br_eth0_2016ce1628e340809a445165de5d6912]"
        },
        "causes": [],
        "code": "VM.1001",
        "description": "Unable to start a vm",
        "details": "cannot find the ID for the namespace[br_eth0_2016ce1628e340809a445165de5d6912]"
    },
    "jobUuid": "83a21a2f81894baca7bb1cbe1a070e2a",
    "success": false
}
```

该物理机的系统环境 
```
[root@localhost ~]# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
[root@localhost ~]# free -mh
              total        used        free      shared  buff/cache   available
Mem:           125G         24G         96G         16M        5.3G        101G
Swap:          4.0G          0B        4.0G
[root@localhost ~]# uname -a
Linux localhost.localdomain 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost ~]# cat /proc/cpuinfo |grep process -c
24
```
创建时 查看 日志文件  /var/log/zstack/zstack-kvmagent.log
```
2018-10-14 22:24:39,092 WARNING [kvmagent.kvmagent] cannot find the ID for the namespace[br_eth0_2016ce1628e340809a445165de5d6912]
Traceback (most recent call last):
  File "/var/lib/zstack/virtualenv/kvm/lib/python2.7/site-packages/kvmagent/kvmagent.py", line 114, in wrap
    return func(*args, **kwargs)
  File "/var/lib/zstack/virtualenv/kvm/lib/python2.7/site-packages/kvmagent/plugins/mevoco.py", line 732, in apply_dhcp
    apply(v)
  File "/var/lib/zstack/virtualenv/kvm/lib/python2.7/site-packages/kvmagent/plugins/mevoco.py", line 628, in apply
    raise Exception('cannot find the ID for the namespace[%s]' % namespace_name)
Exception: cannot find the ID for the namespace[br_eth0_2016ce1628e340809a445165de5d6912]
```

**Comment by quarkonics** [comment]
请使用ZStack官方ISO安装，更多信息也可以加入ZStack的QQ群社区咨询443027683
