### ISSUE TITLE
4.2.32版升级至4.4.40后无法启动主机

### ISSUE THREAD

**Issue by ejzhang** [zstackio/zstack#1325]
![ZStack-StartVM](https://user-images.githubusercontent.com/452491/200751936-1f7c75e9-19a5-4cf6-a5d6-9ef109142564.png)
`failed to start vm[uuid:2b99exxxxxxxxxxxxxxxxxxxxxxx53e9 name:AlmaLinux-8.6] on kvm host[uuid:56f8xxxxxxxxxxxxxxxxx4a75e, ip:192.xx.xx.xx], because Traceback (most recent call last): File "/var/lib/zstack/virtualenv/kvm/lib/python2.7/site-packages/kvmagent/plugins/vm_plugin.py", line 5514, in start_vm self._start_vm(cmd) File "/var/lib/zstack/virtualenv/kvm/lib/python2.7/site-packages/kvmagent/plugins/vm_plugin.py", line 5430, in _start_vm 'unable to start vm[uuid:%s, name:%s], libvirt error: %s' % (cmd.vmInstanceUuid, cmd.vmName, str(e))) KvmError: unable to start vm[uuid:2b99xxxxxxxxxxxxxxxxxxxxxxxx53e9, name:AlmaLinux-8.6], libvirt error: internal error: process exited while connecting to monitor: qemu-kvm: -realtime mlock=off: warning: '-realtime mlock=...' is deprecated, please use '-overcommit mem-lock=...' instead 2022-11-09T04:00:47.423664Z qemu-kvm: -drive file=/zstack_ps/rootVolumes/acct-36c2xxxxxxxxxxxxxxxxxxxxxxxxf22e/vol-fd4axxxxxxxxxxxxxxxxxxxxxxxxe4e7/fd4axxxxxxxxxxxxxxxxxxxxxxxxe4e7.qcow2,format=qcow2,if=none,id=drive-virtio-disk0,serial=fd4axxxxxxxxxxxxxxxxxxxxxxxxe4e7,cache=none: Block format 'qcow2' does not support the option 'serial'`

4.2.32版Bug无法打开控制台，升级至4.4.38版后控制台可以打开，但是启动主机失败，升级至4.4.40版后启动主机仍然失败，请问是什么原因？

**Comment by MaJin1996** [comment]
看一下物理机上使用的 qemu 和 libvirt 的版本

**Comment by ejzhang** [comment]
![ZStack-Qemu-Libvirt](https://user-images.githubusercontent.com/452491/200784676-1f030b8e-0194-478f-8ff8-b13d6dc920b8.png)
Qemu：4.2.0-449，Libvirt：4.1.0-2

**Comment by MaJin1996** [comment]
zstack 4.4.x 版本使用的是 qemu 4.2 + libvirt 4.9.0 
4.1 是几年前的版本
可以升级 libvirt 到 4.9.0 解决。

为了避免还有类似问题，以下命令可以把 host 连带 kernal 升级到 4.18 

zstack-cli执行
UpdateGlobalConfig name="zstack.experimental.repo" value=true category=cluster
UpdateClusterOS excludePackages=python2-crypto uuid=你的集群UUID

**Comment by ejzhang** [comment]
> zstack 4.4.x 版本使用的是 qemu 4.2 + libvirt 4.9.0，但升级 ZStack 不会帮你升级 qemu libvirt 4.1 是几年前我们使用的版本，和 qemu 4.2 并不匹配。 可以升级 libvirt 到 4.9.0 解决。
> 
> 为了避免还有类似问题，以下命令可以把 host 上的 qemu libvirt 升级到推荐版本，kernal 也会升级到 4.18
> 
> zstack-cli执行 UpdateGlobalConfig name="zstack.experimental.repo" value=true category=cluster UpdateClusterOS excludePackages=python2-crypto uuid=你的集群UUID

请问内网如何离线升级？

**Comment by MaJin1996** [comment]
内网用 cli 的升级方法已经在上面贴了，在管理节点执行 cli

**Comment by ejzhang** [comment]
我以为是要联网升级呢，我试一下，多谢！

**Comment by MaJin1996** [comment]
如果只想单独升级 Libvirt，管理节点的 repo 里也包含了 libvirt 4.9.0 的 rpm 
![image](https://user-images.githubusercontent.com/25005574/200800872-a722ac62-b4d8-4382-932a-aa8ed299eac3.png)

**Comment by ejzhang** [comment]
明白，非常感谢！

**Comment by ejzhang** [comment]
![ZStack-Cli](https://user-images.githubusercontent.com/452491/200811167-2db8cfd8-2393-4647-8867-40c10d5e9582.png)
![ZStack-Yum](https://user-images.githubusercontent.com/452491/200811200-b5ffa086-18f3-4a41-9ce4-2afa96597afc.png)
yum更新就可以了吗？更新列表里怎么没有Libvirt？

**Comment by ejzhang** [comment]
已安装Libvirt 4.9.0版，可以正常启动主机了。
PS：不知是否可以直接运行yum update更新？

**Comment by MaJin1996** [comment]
yum check-upgrade --disablerepo=*  --enablerepo=
